name: meal_app
description: Meal Tracker App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & utilities
  image_picker: ^1.1.2
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0

  # Firebase (COMPATIBLE VERSIONS - FIXED)
  firebase_core: ^3.12.2
  firebase_storage: ^12.4.10
  firebase_auth: ^5.5.1
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/